=== nievax/json2xml/examples/controlledvocabulary.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
This Schema was created by the University of Minho                     <http://www.uminho.pt>,
Department of Information Systems                                  <http://www.dsi.uminho.pt> 
for the Controlled-vocabulary Add-on of the HP/MIT's DSpace <http://dspace-dev.dsi.uminho.pt>. 

For more information regarding this schema, please contact the authors: 
Miguel Ferreira <mferreira@dsi.uminho.pt> and
Ana Alice Baptista <analice@dsi.uminho.pt>. 
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="node">
		<xs:annotation>
			<xs:documentation>Element that describes a concept</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="isComposedBy" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Contains the children of this node.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="node" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="isRelatedTo"  minOccurs="0">
					<xs:annotation>
						<xs:documentation>A list of related terms</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="node" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Link to an existing node</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="id" type="xs:IDREF" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
                <!-- becomes mouseover hint in GUI: -->
				<xs:element name="hasNote"      minOccurs="0">
					<xs:annotation>
						<xs:documentation>A note related to this term</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension                 base="xs:string">
								<xs:attribute name="type" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:all>
            <!-- modified: in orig. xsd, it says type="xs:ID", meaning ids must NOT be number strings, but CVs need exactly that -->
			<xs:attribute name="id"             type="xs:string"    use="required"/>
			<xs:attribute name="label"          type="xs:string"    use="required"/>
			<xs:attribute name="selectable"     type="xs:boolean"   default="true"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nievax/json2xml/examples/data-type-v2-target.xml
<?xml version="1.0" encoding="utf-8"?>
<node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="controlledvocabulary.xsd"
                            id="0"      label="data-type-v2">
    <isComposedBy>
        <node               id="1"      label="Kompetenz- und Leistungsdaten"/>
        <node               id="2"      label="Qualitatives, nicht oder gering standardisiertes Datenmaterial"/>
        <node               id="3"      label="Umfrage- und Aggregatedaten"/>
            <node           id="4"      label="Forschungsinstrument">
                <isComposedBy>
                    <node   id="41"     label="Fragebogenskalen"/>
                    <node   id="42"     label="Kompetenztest oder Wissenstest"/>
                    <node   id="43"     label="Ratingmanual"/>                  
                    <node   id="44"     label="Lerntagebuch"/>                  
                </isComposedBy>
            </node>

        <node               id="99"     label="Sonstiges Datenmaterial"/>
    </isComposedBy>
</node>

=== nievax/json2xml/examples/df_Datenformat_target.xml
<?xml version="1.0" encoding="utf-8"?>
       <node id="0" label="data-format" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="controlledvocabulary.xsd">
       <isComposedBy>
       <node id="1" label="Audiovisuell"/>
       <node id="2" label="Datenkollektion">
       <hasNote>
=Sammlung
       </hasNote>

       </node>
       <node id="3" label="DataPaper"/>
       <node id="4" label="Datensatz">
       <hasNote>
Hierunter fallen auch Logdaten (Hinweis: Im Metadatenschema daIra 4.0 kann bei der Auswahl des Resource Type 'Datensatz' als Spezifizierung bei Resource Tpe Free 'Logdaten' eingetragen werden.).
       </hasNote>

       </node>
       <node id="5" label="Event"/>
       <node id="6" label="Bild"/>
       <node id="7" label="Interaktives Objekt"/>
       <node id="8" label="Modell"/>
       <node id="9" label="Physisches Objekt"/>
       <node id="10" label="Service"/>
       <node id="11" label="Software"/>
       <node id="12" label="Audio"/>
       <node id="13" label="Text"/>
       <node id="14" label="Workflow"/>
       <node id="15" label="andere"/>

       </isComposedBy>

       </node>
